# config.py

BOT_TOKEN = "PASTE_YOUR_BOT_TOKEN"
CHANNEL_USERNAME = "@PASTE_YOUR_CHANNEL"

# Filters
INTERNSHIP_MIN = 5000
INTERNSHIP_MAX = 30000
JOB_MIN = 35000

POSTS_PER_TYPE = 5
HOURS_LIMIT = 24
